### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by Yogoda** [OrigamiDev-Pete/MeshBatcher#2]
Hello, I realized the MeshBatcher node can inherit directly from MultiMeshInstance instead of spatial. It simplifies the code a great deal and creates less nodes.

I did the modification on my version and it works very well, the simpler the better I say ;)
https://github.com/Yogoda/MeshBatcher

Also not sure why you are storing the transforms (faster unbatching?). I removed it in my version, it's a lot of data.

Tell me if you want a pull request, but I'm not sure it is worth it.

**Comment by OrigamiDev-Pete** [comment]
I just tried out your version and it's really elegant. I wish I thought about it like that when I first made it!
Storing the transforms for each mesh was indeed an optimisation to speed up the unbatching, though, in practice it saves one call per mesh so I'm not sure how much time it actually would save and I haven't noticed any significant differences whether the transforms were stored or not. So, I think you're right, it probably isn't necessary to store the transforms.

It would be great if you could create a pull request for this. Your contributions have been really valuable, I feel I want to add you as a co-author of the plugin. Let me know if that's something you'd be interested in.
Thanks!

**Comment by Yogoda** [comment]
Thank you, you are really nice :)
Ok, I created a pull request.

You can just leave a "thank you" in the readme, it is enough ;)

It is funny, I had the same idea for multi-mesh instance nodes, create children to be able to modify the position of instances in the editor. And then I found your plugin, great job. It should probably be a core functionality tbh.
