### ISSUE TITLE
Upgrading to godot 4.x

### ISSUE THREAD

**Issue by Sky84** [OrigamiDev-Pete/MeshBatcher#7]
Is it possible to upgrading it to 4.x ?

**Comment by VecterraSoft** [comment]
Its real easy to convert to Godot 4, Here is How:

Rename all of the following in the  two .gd scripts:

-tool to @tool
-Meshinstance to MeshInstance3D
-Spatial to Node3D
-Staticbody to StaticBody3D
-Transform to Transform3D

Thats it!

**Comment by OrigamiDev-Pete** [comment]
Thanks for following this up @VecterraSoft, and apologies @Sky84 for letting this slip my mind.
The main reason I haven't created a Godot 4 version of the plugin is that, as far as I know, Godot 4 does GPU instancing automatically for identical meshes which renders MeshBatcher mostly obsolete.
